CREATE PROC FI_SP_ConsBeneficiario
	@Id BIGINT
AS
BEGIN
	IF(ISNULL(@Id,0) = 0)
		SELECT CPF, NOME, IDCLIENTE, ID 
        FROM BENEFICIARIOS WITH(NOLOCK);
    ELSE
        SELECT CPF, NOME, IDCLIENTE, ID 
        FROM BENEFICIARIOS WITH(NOLOCK) 
        WHERE ID = @ID;
END